### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by rahat-yasir** [PrimozGodec/ImageColorization#1]
Any plan to upload the pre-trained model ?

**Comment by PrimozGodec** [comment]
Hello, weights for pre-trained models are already available in the release. Look https://github.com/PrimozGodec/ImageColorization/releases

They need to be placed inside `data/weights` directory.

**Comment by rahat-yasir** [comment]
Which model should i use for VIDEO colorization?

**Comment by PrimozGodec** [comment]
For video coloring, I suggest using `reg_full_model` which perform best. The model is already chosen when you use the script for video coloring.

**Comment by rahat-yasir** [comment]
For video coloring, i noticed some temporal inconsistency and brightness flickering noise. how did you fix it?

**Comment by PrimozGodec** [comment]
Do you mean temporal inconsistency and brightness flickering between consecutive images? 
That is an issue that nobody fixed it now. The problem appears since every frame is colored separately without looking at the previous/next image. I am planning to try to fix it one day.
