### ISSUE TITLE
Train script and other details

### ISSUE THREAD

**Issue by surabhisnath** [PrimozGodec/ImageColorization#5]
Hello! I went through your repo and found it very useful. I wanted to inquire if you could also provide the script for training, the model script and indicate what type of data are the pre-trained models trained on. Thanks a lot!

**Comment by PrimozGodec** [comment]
Hello, I will try to add it but I cannot promise to make it soon since I am quite busy right now.

**Comment by surabhisnath** [comment]
Thanks!
